# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HomographyGUI.ui'
#
# Created: Sat Dec  5 17:37:35 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(570, 484)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnLoadSource = QtGui.QPushButton(self.centralwidget)
        self.btnLoadSource.setGeometry(QtCore.QRect(20, 0, 121, 27))
        self.btnLoadSource.setObjectName("btnLoadSource")
        self.btnLoadTarget = QtGui.QPushButton(self.centralwidget)
        self.btnLoadTarget.setGeometry(QtCore.QRect(290, 0, 121, 27))
        self.btnLoadTarget.setObjectName("btnLoadTarget")
        self.viewSourceImage = QtGui.QGraphicsView(self.centralwidget)
        self.viewSourceImage.setGeometry(QtCore.QRect(20, 30, 250, 250))
        self.viewSourceImage.setObjectName("viewSourceImage")
        self.viewTargetImage = QtGui.QGraphicsView(self.centralwidget)
        self.viewTargetImage.setGeometry(QtCore.QRect(290, 30, 250, 250))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewTargetImage.sizePolicy().hasHeightForWidth())
        self.viewTargetImage.setSizePolicy(sizePolicy)
        self.viewTargetImage.setObjectName("viewTargetImage")
        self.btnAcquirePoints = QtGui.QPushButton(self.centralwidget)
        self.btnAcquirePoints.setEnabled(False)
        self.btnAcquirePoints.setGeometry(QtCore.QRect(230, 290, 121, 27))
        self.btnAcquirePoints.setCheckable(True)
        self.btnAcquirePoints.setObjectName("btnAcquirePoints")
        self.pointUL = QtGui.QLineEdit(self.centralwidget)
        self.pointUL.setEnabled(False)
        self.pointUL.setGeometry(QtCore.QRect(360, 290, 90, 27))
        self.pointUL.setReadOnly(True)
        self.pointUL.setObjectName("pointUL")
        self.pointUR = QtGui.QLineEdit(self.centralwidget)
        self.pointUR.setEnabled(False)
        self.pointUR.setGeometry(QtCore.QRect(450, 290, 90, 27))
        self.pointUR.setReadOnly(True)
        self.pointUR.setObjectName("pointUR")
        self.pointLL = QtGui.QLineEdit(self.centralwidget)
        self.pointLL.setEnabled(False)
        self.pointLL.setGeometry(QtCore.QRect(360, 320, 90, 27))
        self.pointLL.setReadOnly(True)
        self.pointLL.setObjectName("pointLL")
        self.pointLR = QtGui.QLineEdit(self.centralwidget)
        self.pointLR.setEnabled(False)
        self.pointLR.setGeometry(QtCore.QRect(450, 320, 90, 27))
        self.pointLR.setReadOnly(True)
        self.pointLR.setObjectName("pointLR")
        self.comboEffect = QtGui.QComboBox(self.centralwidget)
        self.comboEffect.setEnabled(False)
        self.comboEffect.setGeometry(QtCore.QRect(320, 360, 221, 27))
        self.comboEffect.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.comboEffect.setAcceptDrops(False)
        self.comboEffect.setFrame(True)
        self.comboEffect.setObjectName("comboEffect")
        self.comboEffect.addItem("")
        self.comboEffect.addItem("")
        self.comboEffect.addItem("")
        self.comboEffect.addItem("")
        self.comboEffect.addItem("")
        self.comboEffect.addItem("")
        self.comboEffect.addItem("")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 360, 41, 17))
        self.label.setObjectName("label")
        self.btnTransform = QtGui.QPushButton(self.centralwidget)
        self.btnTransform.setEnabled(False)
        self.btnTransform.setGeometry(QtCore.QRect(270, 400, 85, 27))
        self.btnTransform.setObjectName("btnTransform")
        self.btnReset = QtGui.QPushButton(self.centralwidget)
        self.btnReset.setEnabled(False)
        self.btnReset.setGeometry(QtCore.QRect(360, 400, 85, 27))
        self.btnReset.setObjectName("btnReset")
        self.btnSave = QtGui.QPushButton(self.centralwidget)
        self.btnSave.setEnabled(False)
        self.btnSave.setGeometry(QtCore.QRect(450, 400, 85, 27))
        self.btnSave.setObjectName("btnSave")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 570, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLoadSource.setText(QtGui.QApplication.translate("MainWindow", "Load Source ...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLoadTarget.setText(QtGui.QApplication.translate("MainWindow", "Load Target ...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAcquirePoints.setText(QtGui.QApplication.translate("MainWindow", "Acquire Points", None, QtGui.QApplication.UnicodeUTF8))
        self.comboEffect.setItemText(0, QtGui.QApplication.translate("MainWindow", "Nothing", None, QtGui.QApplication.UnicodeUTF8))
        self.comboEffect.setItemText(1, QtGui.QApplication.translate("MainWindow", "Rotate 90", None, QtGui.QApplication.UnicodeUTF8))
        self.comboEffect.setItemText(2, QtGui.QApplication.translate("MainWindow", "Rotate 180", None, QtGui.QApplication.UnicodeUTF8))
        self.comboEffect.setItemText(3, QtGui.QApplication.translate("MainWindow", "Rotate 270", None, QtGui.QApplication.UnicodeUTF8))
        self.comboEffect.setItemText(4, QtGui.QApplication.translate("MainWindow", "Flip Horizontally", None, QtGui.QApplication.UnicodeUTF8))
        self.comboEffect.setItemText(5, QtGui.QApplication.translate("MainWindow", "Flip Vertically", None, QtGui.QApplication.UnicodeUTF8))
        self.comboEffect.setItemText(6, QtGui.QApplication.translate("MainWindow", "Transpose", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Effect", None, QtGui.QApplication.UnicodeUTF8))
        self.btnTransform.setText(QtGui.QApplication.translate("MainWindow", "Transform", None, QtGui.QApplication.UnicodeUTF8))
        self.btnReset.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))

