# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created: Mon Nov  9 13:44:03 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(424, 248)
        self.textBrowser = QtGui.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(10, 20, 391, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_0 = QtGui.QPushButton(Dialog)
        self.pushButton_0.setGeometry(QtCore.QRect(10, 160, 151, 27))
        self.pushButton_0.setObjectName("pushButton_0")
        self.checkBox = QtGui.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(190, 200, 231, 22))
        self.checkBox.setObjectName("checkBox")
        self.spinBox = QtGui.QSpinBox(Dialog)
        self.spinBox.setGeometry(QtCore.QRect(110, 210, 55, 27))
        self.spinBox.setObjectName("spinBox")
        self.pushButton_1 = QtGui.QPushButton(Dialog)
        self.pushButton_1.setGeometry(QtCore.QRect(10, 130, 71, 27))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtGui.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 130, 71, 27))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtGui.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(170, 130, 71, 27))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtGui.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 100, 71, 27))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtGui.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(90, 100, 71, 27))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtGui.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(170, 100, 71, 27))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtGui.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 70, 71, 27))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtGui.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(90, 70, 71, 27))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtGui.QPushButton(Dialog)
        self.pushButton_9.setGeometry(QtCore.QRect(170, 70, 71, 27))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_min = QtGui.QPushButton(Dialog)
        self.pushButton_min.setGeometry(QtCore.QRect(250, 130, 71, 27))
        self.pushButton_min.setObjectName("pushButton_min")
        self.pushButton_mul = QtGui.QPushButton(Dialog)
        self.pushButton_mul.setGeometry(QtCore.QRect(250, 100, 71, 27))
        self.pushButton_mul.setObjectName("pushButton_mul")
        self.pushButton_div = QtGui.QPushButton(Dialog)
        self.pushButton_div.setGeometry(QtCore.QRect(250, 70, 71, 27))
        self.pushButton_div.setObjectName("pushButton_div")
        self.pushButton_add = QtGui.QPushButton(Dialog)
        self.pushButton_add.setGeometry(QtCore.QRect(250, 160, 71, 27))
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_period = QtGui.QPushButton(Dialog)
        self.pushButton_period.setGeometry(QtCore.QRect(170, 160, 71, 27))
        self.pushButton_period.setObjectName("pushButton_period")
        self.pushButton_clear = QtGui.QPushButton(Dialog)
        self.pushButton_clear.setGeometry(QtCore.QRect(330, 70, 81, 51))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_equal = QtGui.QPushButton(Dialog)
        self.pushButton_equal.setGeometry(QtCore.QRect(330, 140, 81, 51))
        self.pushButton_equal.setObjectName("pushButton_equal")
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 210, 101, 17))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_0.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Dialog", "Display Thousands\' Separator", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_1.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("Dialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("Dialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("Dialog", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_min.setText(QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_mul.setText(QtGui.QApplication.translate("Dialog", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_div.setText(QtGui.QApplication.translate("Dialog", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_add.setText(QtGui.QApplication.translate("Dialog", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_period.setText(QtGui.QApplication.translate("Dialog", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_clear.setText(QtGui.QApplication.translate("Dialog", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_equal.setText(QtGui.QApplication.translate("Dialog", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Decimal Digits", None, QtGui.QApplication.UnicodeUTF8))

