#! /bin/bash
#
#########################
#      $Author: ee364f03 $
#      $Date: 2015-08-25 16:55:34 -0400 (Tue, 25 Aug 2015) $     
#      $HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/F15/students/ee364f03/Lab00/Script3 $  
#      $Revision: 80175 $   
#                 
#########################


for (( I=$1; I>=0; I--))
do
	if ((I%3 == 0))
	then echo  ${I}
	fi
done

exit 0
